"""Emit ``docs/disasm/module-map.md`` from the index.

Kept separate from :mod:`tools.alf.modules` so that the attribution logic has no
opinion about presentation, and so regenerating the document never needs a
re-index::

    python tools/alf/module_map.py --db <index> --out docs/disasm/module-map.md

The document contains only addresses, sizes and file *names* -- no instruction
text -- so it is safe to commit, unlike the index itself.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.alf import db as dbmod
from tools.alf.modules import module_ranges

CONFIDENCE_NOTES = {
    "high": "function contains an `assert()` naming this file",
    "medium": "function lies between two same-file assert anchors (linker locality)",
    "low": "no anchor; every known direct caller resolves to this file",
}


def render(conn, *, min_span: int = 512) -> str:
    ranges = module_ranges(conn)
    total_funcs = conn.execute("SELECT COUNT(*) FROM functions").fetchone()[0]
    literals = conn.execute("SELECT COUNT(*) FROM module_strings").fetchone()[0]
    anchored_files = conn.execute(
        "SELECT COUNT(DISTINCT filename) FROM module_refs"
    ).fetchone()[0]
    per_conf = dict(
        conn.execute(
            "SELECT confidence, COUNT(*) FROM functions GROUP BY confidence"
        ).fetchall()
    )

    out: list[str] = []
    out.append("# Imperialism.exe module map\n")
    out.append(
        "Generated by `tools/alf/module_map.py` from the local disassembly index.\n"
        "Do not edit by hand.\n"
    )
    out.append(f"Generated {_dt.date.today().isoformat()}.\n")
    out.append(
        "## Method\n\n"
        "The retail executable was built with `assert()` enabled, so MSVC's assert macro\n"
        "left `push <line>; push <\"D:\\\\Ambit\\\\...\\\\File.cpp\">; call <handler>` at every\n"
        "assert site. Those string literals are the only symbolic information the binary\n"
        "leaks. Each site anchors the enclosing function to a translation unit; because\n"
        "the linker emits each `.obj`'s code contiguously, the gaps between same-file\n"
        "anchors can be filled in with reasonable confidence.\n\n"
        "Confidence levels:\n\n"
        "| level | meaning |\n| --- | --- |\n"
        + "".join(f"| `{k}` | {v} |\n" for k, v in CONFIDENCE_NOTES.items())
        + "\n"
    )
    out.append(
        f"- source filename literals found in `.data`: **{literals}**\n"
        f"- of those, referenced by code we could locate: **{anchored_files}**\n"
        f"- functions detected: **{total_funcs:,}**\n"
        + "".join(
            f"- functions at `{k}` confidence: **{v:,}**\n"
            for k, v in sorted(per_conf.items(), key=lambda kv: kv[0])
        )
        + "\n"
    )

    # --- per-module summary ------------------------------------------------
    summary: dict[str, dict] = {}
    for r in ranges:
        s = summary.setdefault(
            r.filename, {"funcs": 0, "bytes": 0, "anchors": 0, "spans": 0, "conf": set()}
        )
        s["funcs"] += r.function_count
        s["bytes"] += r.end - r.start + 1  # range end is inclusive
        s["anchors"] += r.anchor_count
        s["spans"] += 1
        s["conf"].add(r.confidence)

    out.append("## Modules\n\n")
    out.append(
        "| source file | assert anchors | functions | approx. bytes | spans | best confidence |\n"
        "| --- | ---: | ---: | ---: | ---: | --- |\n"
    )
    order = {"high": 0, "medium": 1, "low": 2}
    for name, s in sorted(summary.items(), key=lambda kv: -kv[1]["bytes"]):
        best = sorted(s["conf"], key=lambda c: order.get(c, 9))[0]
        out.append(
            f"| `{name}` | {s['anchors']} | {s['funcs']} | {s['bytes']:,} | "
            f"{s['spans']} | `{best}` |\n"
        )

    unreferenced = [
        row[0]
        for row in conn.execute(
            "SELECT filename FROM module_strings WHERE filename NOT IN "
            "(SELECT DISTINCT filename FROM module_refs) ORDER BY filename"
        )
    ]
    if unreferenced:
        out.append(
            "\n### Known but unlocated\n\n"
            "These filename literals exist in `.data` but no instruction we recognised\n"
            "loads their address, so they could not be placed. Most likely their assert\n"
            "sites were compiled out, or the address reaches the push through a register.\n\n"
        )
        for name in unreferenced:
            out.append(f"- `{name}`\n")

    # --- address ranges ----------------------------------------------------
    out.append("\n## Address ranges\n\n")
    shown = [r for r in ranges if r.anchor_count or (r.end - r.start) >= min_span]
    out.append(
        "Contiguous runs of same-file, same-confidence functions. Ranges are *not*\n"
        "exhaustive -- everything not listed is unattributed -- and this table shows\n"
        f"only runs that contain an assert anchor or span at least {min_span} bytes\n"
        f"({len(shown)} of {len(ranges)}). For the complete list, including the small\n"
        "fragments, run `python -m tools.alf.query modules --ranges`.\n\n"
    )
    out.append("| range | size | source file | confidence | funcs | anchors |\n")
    out.append("| --- | ---: | --- | --- | ---: | ---: |\n")
    for r in shown:
        out.append(
            f"| `{r.start:08X}`–`{r.end:08X}` | {r.end - r.start:,} | `{r.filename}` | "
            f"`{r.confidence}` | {r.function_count} | {r.anchor_count} |\n"
        )
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=str(dbmod.default_db_path()))
    ap.add_argument("--out", default="docs/disasm/module-map.md")
    ap.add_argument("--min-span", type=int, default=512,
                    help="smallest anchorless range to list in the ranges table")
    args = ap.parse_args(argv)
    conn = dbmod.connect(args.db, create=False)
    try:
        text = render(conn, min_span=args.min_span)
    finally:
        conn.close()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
